export const categoryBrowseData = [
  {
    id: 1,
    slug: "adult-care",
    name: "Adult Care",
    description: "Compassionate care for seniors and adults",
    basePrice: 10000,
  },
  {
    id: 2,
    slug: "post-surgery-care",
    name: "Post Surgery Care",
    description: "Recovery support after surgery or hospital discharge",
    basePrice: 10000,
  },
  {
    id: 3,
    slug: "child-care",
    name: "Child Care",
    description: "Professional childcare and nanny services",
    basePrice: 10000,
  },
  {
    id: 4,
    slug: "pet-care",
    name: "Pet Care",
    description: "Pet minding, dog walking, and pet companionship",
    basePrice: 10000,
  },
  {
    id: 5,
    slug: "home-care",
    name: "Home Care",
    description: "General home assistance and daily living support",
    basePrice: 10000,
  },
  {
    id: 6,
    slug: "special-needs-care",
    name: "Special Needs Care",
    description: "Specialized care for individuals with special needs",
    basePrice: 10000,
  },
  {
    id: 7,
    slug: "medical-support",
    name: "Medical Support",
    description: "Nursing care and medical assistance",
    basePrice: 10000,
  },
  {
    id: 8,
    slug: "mobility-support",
    name: "Mobility Support",
    description: "Mobility assistance and fall prevention",
    basePrice: 10000,
  },
  {
    id: 9,
    slug: "therapy-wellness",
    name: "Therapy & Wellness",
    description: "Physical therapy and wellness support",
    basePrice: 10000,
  },
  {
    id: 10,
    slug: "palliative",
    name: "Palliative",
    description: "Palliative care and emotional support",
    basePrice: 10000,
  },
];
