name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pg123
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: |
          cd backend
          dotnet restore

      - name: Build
        run: |
          cd backend
          dotnet build --no-restore --verbosity normal

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:pg123@localhost:5432/test_db
        run: |
          cd backend
          dotnet test --no-build --verbosity normal
